### ISSUE TITLE
Jade on TTGO T-display?

### ISSUE THREAD

**Issue by biterminator** [Blockstream/Jade#19]
Any help for running Jade wallet on TTGO T-display device?

**Comment by JamieDriver** [comment]
Support for this device should be being added in the next fw release.

**Comment by biterminator** [comment]
> Support for this device should be being added in the next fw release - the config should soon be available in master branch.

Thank you!

Please post some simple instructions for instalation when released.

**Comment by JamieDriver** [comment]
Hi,
We have merged changes/config to support TTGO T-display to master.
This means you should be able to build and flash the firmware as in the README.
The only change you'll need to make, is instead of:
```
cp configs/sdkconfig_jade.defaults sdkconfig.defaults
```
you'll need to:
```
cp configs/sdkconfig_display_ttgo_tdisplay.defaults sdkconfig.defaults
```

Note: on the TTGO T-display board the buttons individually correspond to 'left' and 'right' actions, and both together as 'select'.

**Comment by JamieDriver** [comment]
Is this working for you now ?

**Comment by JamieDriver** [comment]
Closing - should now be working.
